[workspace]
members = ["ethmutator", "afl_ethmutator", "utils"]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true

[profile.bench]
lto = true
codegen-units = 1
opt-level = 3
debug = true
